export const FETCHALLFOODS = "FETCHALLFOODS";

export const ADDFOOD = "ADDFOOD";

export const EDITFOOD = "EDITFOOD";

export const DELETEFOOD = "DELETEFOOD";

export const FETCHPRODUCTS = "FETCHPRODUCTS";

export const ADDPRODUCT = "ADDPRODUCT";

export const EDITPRODUCT = "EDITPRODUCT";

export const TOGGLEACTIVERESTAURANT = "TOGGLEACTIVERESTAURANT";

export const DELETEPRODUCT = "DELETEPRODUCT";

export const FETCHALLRESTAURANTS = "FETCHALLRESTAURANTS";

export const ADDRESTAURANT = "ADDRESTAURANT";

export const EDITRESTAURANT = "EDITRESTAURANT";

export const DELETERESTAURANT = "DELETERESTAURANT";

export const FETCHALLORDERS = "FETCHALLORDERS";

export const EDITORDER = "EDITORDER";
